import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Exo_2 } from 'next/font/google'

const poppins = Poppins({weight: "400", subsets:['latin']})
const exo2 = Exo_2({weight: "400", subsets:['latin']})

export const metadata: Metadata = {
  title: "APEX Dance Crew",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
